---
- name: "Validate bash_config variables"
  tags: [bash, validation, always]
  ansible.builtin.fail:
    msg: "bash_config variable is not defined or is not mapping"
  when: bash_config is not defined or bash_config is not mapping


- name: "Configure bash"
  tags: ["bash"]
  block:
    - name: "Configure bash: basrc"
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        block: |
          export HISTTIMEFORMAT="{{ bash_config.histtimeformat }}"
          export HISTSIZE={{ bash_config.histsize }}
          export HISTFILESIZE={{ bash_config.histfilesize }}
          PROMPT_COMMAND="{{ bash_config.prompt_command }}"
        create: true
        backup: true
        mode: "0644"
        owner: "root"
        group: "root"
  rescue:
    - name: "Configure bash: failure"
      ansible.builtin.debug:
        msg: "Bash configuration failed for {{ inventory_hostname }}"
      tags: [bash, error]


- name: "Verify bash configuration"
  tags: [bash, verification]
  block:
    - name: "Verify bash configuration: syntax"
      ansible.builtin.command: "bash -n /etc/bash.bashrc"
      register: bash_config_test
      changed_when: false
      failed_when: bash_config_test.rc != 0

    - name: "Verify bash configuration: debug"
      ansible.builtin.debug:
        msg: "{{ bash_config_test.stdout }}"
      when: debug | default(false) | bool
