#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

packages:
  - tzdata
  - ca-certificates
  - apt-transport-https
  - gnupg
  - curl

bootcmd:
  - |
    VG_ID="vg_data"
    LV_ID="lv_data"
    LVM_DEV="/dev/mapper/${VG_ID}-${LV_ID}"
    GITLAB_DATA="/var/opt/gitlab/"
    if [ -b "${LVM_DEV}" ]; then
      mkdir -p "${GITLAB_DATA}"
      if blkid "${LVM_DEV}" | grep -q 'TYPE="xfs"'; then
        mount "${LVM_DEV}" "${GITLAB_DATA}"
        if ! grep -q "${LVM_DEV}" /etc/fstab; then
          echo "${LVM_DEV}  ${GITLAB_DATA}  xfs defaults  0   0" >> /etc/fstab
        fi
      fi
    fi

runcmd:
  - curl -fsSL "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey" | gpg --dearmor -o /usr/share/keyrings/gitlab-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/gitlab-archive-keyring.gpg] https://packages.gitlab.com/gitlab/gitlab-ce/debian bookworm main" | tee /etc/apt/sources.list.d/gitlab_gitlab-ce.list
  - apt update
  - EXTERNAL_URL="https://git.metrika-online.ru" apt install -y gitlab-ce
  - |
    cat << EOF >> /etc/gitlab/gitlab.rb
    gitlab_rails['gitlab_duo_features_enabled'] = false
    nginx['proxy_protocol'] = true
    gitlab_workhorse['proxy_protocol'] = true
    EOF
    gitlab-ctl reconfigure
  - systemctl status apt-daily.service

final_message: "GitLab configuration completed successfully"
