---
- name: "Validate variables"
  tags: [debian, validation, always]
  block:
    - name: "Validate variables: updates_unattended_upgrades"
      ansible.builtin.fail:
        msg: "updates_unattended_upgrades variable is not defined or is not a dictionary"
      when: updates_unattended_upgrades is not defined or updates_unattended_upgrades is not mapping


- name: "Configure updates_unattended_upgrades"
  when: updates_unattended_upgrades.enabled
  tags: [debian, apt, security]
  block:
    - name: "Configure updates_unattended_upgrades: 50unattended-upgrades template"
      ansible.builtin.template:
        src: "apt.conf.d/50unattended-upgrades.j2"
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: "apt configuration changed"

    - name: "Configure updates_unattended_upgrades: 20auto-upgrades template"
      ansible.builtin.template:
        src: "apt.conf.d/20auto-upgrades.j2"
        dest: "/etc/apt/apt.conf.d/20auto-upgrades"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: "apt configuration changed"
  rescue:
    - name: "Configure updates_unattended_upgrades: failure"
      ansible.builtin.debug:
        msg: "updates_unattended_upgrades configuration failed for {{ inventory_hostname }}"
      tags: [debian, apt, security, error]


- name: "Verify updates_unattended_upgrades configuration"
  tags: [debian, apt, security, verification]
  block:
    - name: "Verify updates_unattended_upgrades configuration: syntax"
      ansible.builtin.command: "unattended-upgrades --dry-run --debug"
      register: updates_unattended_upgrades_test
      changed_when: false
      failed_when: updates_unattended_upgrades_test.rc != 0

    - name: "Verify updates_unattended_upgrades configuration: debug"
      ansible.builtin.debug:
        msg: "{{ updates_unattended_upgrades_test.stdout }}"
      when: debug | default(false) | bool
