---
- name: "Validate chrony variables"
  tags: [chrony, validation, always]
  ansible.builtin.fail:
    msg: "chrony_ntp_servers variable is not defined or is not sequence"
  when:
    - chrony_ntp_servers is not defined or chrony_ntp_servers is not sequence


- name: "Chrony configuration"
  tags: [chrony]
  block:
    - name: "Chrony configuration: template"
      ansible.builtin.template:
        src: "chrony.conf.j2"
        dest: "/etc/chrony/chrony.conf"
        owner: root
        group: "root"
        mode: "0644"
      register: chrony_config_changed
      notify: chrony configuration changed
  rescue:
    - name: "Chrony configuration: failure"
      ansible.builtin.debug:
        msg: "Chrony configuration failed for {{ inventory_hostname }}"
      tags: [chrony, error]


- name: "Verify chrony configuration"
  tags: [chrony, verification]
  block:
    - name: "Verify chrony configuration: syntax"
      ansible.builtin.command: "chronyd -Q -d -n"
      register: chrony_config_test
      changed_when: false
      failed_when: chrony_config_test.rc != 0

    - name: "Verify chrony configuration: chronyc sources"
      ansible.builtin.command: "chronyc sources"
      register: chrony_sources
      changed_when: false

    - name: "Verify chrony configuration: debug"
      ansible.builtin.debug:
        msg: "{{ chrony_sources.stdout }}"
      when: debug | default(false) | bool
