---
- name: "Validate SSH variables"
  ansible.builtin.fail:
    msg: "ssh_config variable is not defined or is not a dictionary"
  when: ssh_config is not defined or ssh_config is not mapping
  tags: [ssh, validation]

- name: "SSH configuration"
  tags: [ssh, security]
  block:
    - name: "SSH configuration: template"
      ansible.builtin.template:
        src: "sshd_config.j2"
        dest: "/etc/ssh/sshd_config"
        owner: "root"
        group: "root"
        mode: "0644"
        validate: "/usr/sbin/sshd -t -f %s"
      register: sshd_config_changed
      notify: ssh configuration changed
  rescue:
    - name: "SSH configuration: failure"
      ansible.builtin.debug:
        msg: "SSH configuration failed for {{ inventory_hostname }}"
      tags: [ssh, security]

- name: "Verify SSH configuration"
  tags: [ssh, verification]
  block:
    - name: "Verify SSH configuration: syntax"
      ansible.builtin.command: "/usr/sbin/sshd -T"
      register: ssh_config_test
      changed_when: false
      failed_when: ssh_config_test.rc != 0

    - name: "Verify SSH configuration: debug"
      ansible.builtin.debug:
        msg: "{{ ssh_config_test.stdout }}"
      when: debug | default(false) | bool
